title: Meghan Pokorski
logo: assets/img/new_headshot.jpg
description: >
  <br>
  Results-driven engineering professional transitioning to analytics, skilled in Agile methodologies, machine learning, and data analysis. 
  Expertise in developing data-informed strategies, managing projects, and driving product development through market research and customer feedback. 
  Proven ability to collaborate with cross-functional teams, deliver high-quality results, and communicate insights using Python, SQL, and Tableau. 
  Adept at creating technical designs and actionable recommendations to enhance product positioning and market understanding.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/meghan-pokorski-0764646a/">LinkedIn</a>
  <br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
