title: Meghan Pokorski
logo: assets/img/profile_picture.jpg
description: >
  Experienced engineering professional transitioning to data science. Skilled in Agile methodologies, machine learning,
  and data analysis with hands-on experience in Python, SQL, and data visualization.
  <br>
  <a href="https://www.linkedin.com/in/meghan-pokorski-0764646a/">LinkedIn</a>
  <br>
  <a href="https://github.com/MeghanPokorski">GitHub Profile</a>

show_downloads: false
theme: jekyll-theme-minimal
