title: Meghan Pokorski
logo: assets/img/new_headshot.jpg
description: >
  <br>
  Experienced engineering professional transitioning to data science. Skilled in Agile methodologies, machine learning,
  and data analysis with hands-on experience in Python, SQL, and data visualization.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/meghan-pokorski-0764646a/">LinkedIn</a>
  <br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
